/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOnPreferenceDialog: typeof import('./src/components/AddOnPreferenceDialog.vue')['default']
    AttendeeFormControl: typeof import('./src/components/AttendeeFormControl.vue')['default']
    BookingEventInfo: typeof import('./src/components/BookingEventInfo.vue')['default']
    BookingFinancialSummary: typeof import('./src/components/BookingFinancialSummary.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingHeader: typeof import('./src/components/BookingHeader.vue')['default']
    BookingSummary: typeof import('./src/components/BookingSummary.vue')['default']
    CancellationRequestDialog: typeof import('./src/components/CancellationRequestDialog.vue')['default']
    CancellationRequestNotice: typeof import('./src/components/CancellationRequestNotice.vue')['default']
    EventDetailsHeader: typeof import('./src/components/EventDetailsHeader.vue')['default']
    EventSponsorForm: typeof import('./src/components/EventSponsorForm.vue')['default']
    ProfileView: typeof import('./src/components/ProfileView.vue')['default']
    RestrictionNotices: typeof import('./src/components/RestrictionNotices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorLogoUploader: typeof import('./src/components/SponsorLogoUploader.vue')['default']
    SponsorshipPaymentDialog: typeof import('./src/components/SponsorshipPaymentDialog.vue')['default']
    SuccessMessage: typeof import('./src/components/SuccessMessage.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard.vue')['default']
    TicketsSection: typeof import('./src/components/TicketsSection.vue')['default']
    TicketTransferDialog: typeof import('./src/components/TicketTransferDialog.vue')['default']
    TransferTicketDialog: typeof import('./src/components/TransferTicketDialog.vue')['default']
  }
}
