/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOnPreferenceDialog: typeof import('./src/components/AddOnPreferenceDialog.vue')['default']
    AttendeeFormControl: typeof import('./src/components/AttendeeFormControl.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingSummary: typeof import('./src/components/BookingSummary.vue')['default']
    LucideCheckCircle: typeof import('~icons/lucide/check-circle')['default']
    LucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TicketCard: typeof import('./src/components/TicketCard.vue')['default']
    TicketTransferDialog: typeof import('./src/components/TicketTransferDialog.vue')['default']
    TransferTicketDialog: typeof import('./src/components/TransferTicketDialog.vue')['default']
  }
}
