/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOnPreferenceDialog: typeof import('./src/components/AddOnPreferenceDialog.vue')['default']
    AttendeeFormControl: typeof import('./src/components/AttendeeFormControl.vue')['default']
    BookingEventInfo: typeof import('./src/components/BookingEventInfo.vue')['default']
    BookingFinancialSummary: typeof import('./src/components/BookingFinancialSummary.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingSummary: typeof import('./src/components/BookingSummary.vue')['default']
    CancellationRequestDialog: typeof import('./src/components/CancellationRequestDialog.vue')['default']
    EventSponsorForm: typeof import('./src/components/EventSponsorForm.vue')['default']
    LucideCheckCircle: typeof import('~icons/lucide/check-circle')['default']
    LucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    LucideGift: typeof import('~icons/lucide/gift')['default']
    LucideInfo: typeof import('~icons/lucide/info')['default']
    LucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
    LucideX: typeof import('~icons/lucide/x')['default']
    LucideXCircle: typeof import('~icons/lucide/x-circle')['default']
    ProfileView: typeof import('./src/components/ProfileView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorLogoUploader: typeof import('./src/components/SponsorLogoUploader.vue')['default']
    SponsorshipPaymentDialog: typeof import('./src/components/SponsorshipPaymentDialog.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard.vue')['default']
    TicketTransferDialog: typeof import('./src/components/TicketTransferDialog.vue')['default']
    TransferTicketDialog: typeof import('./src/components/TransferTicketDialog.vue')['default']
  }
}
